In [ ]:
import os
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
os.chdir('/content/drive/MyDrive/Time Series')

In [ ]:
ls

'ARIMA Model.ipynb'           'Naive Smoothing technique.ipynb'
'ARIMA Model New.ipynb'        PCA.ipynb
'Auto Regression.ipynb'        regression_data.xlsx
 breast-cancer.data            Regression.ipynb
'Breast Cancer.ipynb'          sales_data.csv
 Debourgh-Sales.xlsx           SmoothingTechniques.ipynb
'First Time Series.ipynb'      Social_Network_Ads.csv
'Forcasting 2.ipynb'           Untitled0.ipynb
 Forcasting.ipynb              Untitled1.ipynb
 Microsoft_Stock.csv           us_airline_carrier_passenger.csv
'Microsoft Stock.ipynb'        Wine.csv
'Multiplicative model.ipynb'


In [ ]:
df = pd.read_csv('breast-cancer.data', sep = ',', header = 0, names = ['Class', 'age', 'menopause', 'tumor-size', 'inv-nodes', 'node-caps', 'deg-malig', 'breast', 'breast-quad', 'irradiat'])

In [ ]:
df.head()

Class    age menopause  ... breast breast-quad irradiat
0  no-recurrence-events  40-49   premeno  ...  right    right_up       no
1  no-recurrence-events  40-49   premeno  ...   left    left_low       no
2  no-recurrence-events  60-69      ge40  ...  right     left_up       no
3  no-recurrence-events  40-49   premeno  ...  right   right_low       no
4  no-recurrence-events  60-69      ge40  ...   left    left_low       no

[5 rows x 10 columns]

In [ ]:
df.dtypes

Class          object
age            object
menopause      object
tumor-size     object
inv-nodes      object
node-caps      object
deg-malig       int64
breast         object
breast-quad    object
irradiat       object
dtype: object

In [ ]:
df.shape

(285, 10)

In [ ]:
df.isnull().sum()

Class          0
age            0
menopause      0
tumor-size     0
inv-nodes      0
node-caps      0
deg-malig      0
breast         0
breast-quad    0
irradiat       0
dtype: int64

In [ ]:
sum(df['node-caps'] == '?')

8

In [ ]:
df['node-caps'].value_counts()

no     221
yes     56
?        8
Name: node-caps, dtype: int64

In [ ]:
pd.crosstab(df['Class'], df['node-caps'])

node-caps             ?   no  yes
Class                            
no-recurrence-events  5  170   25
recurrence-events     3   51   31

In [ ]:
df['node-caps'] = np.where(df['node-caps'] == '?', 'no', df['node-caps'])

In [ ]:
df['node-caps'].value_counts()

no     229
yes     56
Name: node-caps, dtype: int64

In [ ]:
pd.crosstab(df['Class'], df['breast-quad'])

breast-quad           ?  central  left_low  left_up  right_low  right_up
Class                                                                   
no-recurrence-events  0       17        74       71         18        20
recurrence-events     1        4        35       26          6        13

In [ ]:
df['breast-quad'] = np.where(df['breast-quad'] == '?', 'left_low', df['breast-quad'])

In [ ]:
pd.crosstab(df['Class'], df['breast-quad'])

breast-quad           central  left_low  left_up  right_low  right_up
Class                                                                
no-recurrence-events       17        74       71         18        20
recurrence-events           4        36       26          6        13

In [ ]:
df.head()

Class    age menopause  ... breast breast-quad irradiat
0  no-recurrence-events  40-49   premeno  ...  right    right_up       no
1  no-recurrence-events  40-49   premeno  ...   left    left_low       no
2  no-recurrence-events  60-69      ge40  ...  right     left_up       no
3  no-recurrence-events  40-49   premeno  ...  right   right_low       no
4  no-recurrence-events  60-69      ge40  ...   left    left_low       no

[5 rows x 10 columns]

In [ ]:
df['age'].value_counts()

50-59    96
40-49    90
60-69    57
30-39    35
70-79     6
20-29     1
Name: age, dtype: int64

In [ ]:
df['age1'] = df['tumor-size'].str.split('-', expand = True)[0]
df['age2'] = df['tumor-size'].str.split('-', expand = True)[1]

In [ ]:
df.head()

Class    age menopause  ... irradiat age1 age2
0  no-recurrence-events  40-49   premeno  ...       no   20   24
1  no-recurrence-events  40-49   premeno  ...       no   20   24
2  no-recurrence-events  60-69      ge40  ...       no   15   19
3  no-recurrence-events  40-49   premeno  ...       no    0    4
4  no-recurrence-events  60-69      ge40  ...       no   15   19

[5 rows x 12 columns]

In [ ]:
df[['age1', 'age2']] = df[['age1', 'age2']].astype(int)

In [ ]:
df.dtypes

Class          object
age            object
menopause      object
tumor-size     object
inv-nodes      object
node-caps      object
deg-malig       int64
breast         object
breast-quad    object
irradiat       object
age1            int64
age2            int64
dtype: object

In [ ]:
df['mean-tumor'] = (df['age1'] + df['age2']) / 2

In [ ]:
df.drop(['age1', 'age2'], axis = 1, inplace = True)

In [ ]:
df.dtypes

Class           object
age             object
menopause       object
tumor-size      object
inv-nodes       object
node-caps       object
deg-malig        int64
breast          object
breast-quad     object
irradiat        object
mean-tumor     float64
dtype: object

In [ ]:
df.head()

Class    age menopause  ... breast-quad irradiat mean-tumor
0  no-recurrence-events  40-49   premeno  ...    right_up       no       22.0
1  no-recurrence-events  40-49   premeno  ...    left_low       no       22.0
2  no-recurrence-events  60-69      ge40  ...     left_up       no       17.0
3  no-recurrence-events  40-49   premeno  ...   right_low       no        2.0
4  no-recurrence-events  60-69      ge40  ...    left_low       no       17.0

[5 rows x 11 columns]

In [ ]:
df['age1'] = df['age'].str.split('-', expand = True)[0]
df['age2'] = df['age'].str.split('-', expand = True)[1]

In [ ]:
df[['age1', 'age2']] = df[['age1', 'age2']].astype(int)

In [ ]:
df['mean-age'] = (df['age1'] + df['age2']) / 2

In [ ]:
df.drop(['age1', 'age2'], axis = 1, inplace = True)

In [ ]:
df.head()

Class    age menopause  ... irradiat mean-tumor mean-age
0  no-recurrence-events  40-49   premeno  ...       no       22.0     44.5
1  no-recurrence-events  40-49   premeno  ...       no       22.0     44.5
2  no-recurrence-events  60-69      ge40  ...       no       17.0     64.5
3  no-recurrence-events  40-49   premeno  ...       no        2.0     44.5
4  no-recurrence-events  60-69      ge40  ...       no       17.0     64.5

[5 rows x 12 columns]

In [ ]:
df.drop(['age', 'tumor-size'], axis = 1, inplace = True)

In [ ]:
df['node-size'] = (df['inv-nodes'].str.split('-', expand = True)[1]).astype(int)


In [ ]:
df.head()

Class menopause inv-nodes  ... mean-tumor  mean-age node-size
0  no-recurrence-events   premeno       0-2  ...       22.0      44.5         2
1  no-recurrence-events   premeno       0-2  ...       22.0      44.5         2
2  no-recurrence-events      ge40       0-2  ...       17.0      64.5         2
3  no-recurrence-events   premeno       0-2  ...        2.0      44.5         2
4  no-recurrence-events      ge40       0-2  ...       17.0      64.5         2

[5 rows x 11 columns]

In [ ]:
df.drop('inv-nodes', axis  = 1, inplace = True)

In [ ]:
df['Class'].value_counts()

no-recurrence-events    200
recurrence-events        85
Name: Class, dtype: int64

In [ ]:
df['Class'] = (np.where(df['Class'] == 'no-recurrence-events', 1, 0)).astype(int)

In [ ]:
pd.crosstab(df['Class'], df['menopause'])

menopause  ge40  lt40  premeno
Class                         
0            35     2       48
1            94     5      101

In [ ]:
df['Class'].value_counts()

1    200
0     85
Name: Class, dtype: int64

In [ ]:
object = [feature for feature in df.columns if df[feature].dtypes == 'O']

In [ ]:
object

['menopause', 'node-caps', 'breast', 'breast-quad', 'irradiat']

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
for feature in object:
  df[feature] = LabelEncoder().fit_transform(df[feature])

In [ ]:
df.head()

Class  menopause  node-caps  ...  mean-tumor  mean-age  node-size
0      1          2          0  ...        22.0      44.5          2
1      1          2          0  ...        22.0      44.5          2
2      1          0          0  ...        17.0      64.5          2
3      1          2          0  ...         2.0      44.5          2
4      1          0          0  ...        17.0      64.5          2

[5 rows x 10 columns]

In [ ]:
df.dtypes

Class            int64
menopause        int64
node-caps        int64
deg-malig        int64
breast           int64
breast-quad      int64
irradiat         int64
mean-tumor     float64
mean-age       float64
node-size        int64
dtype: object

In [ ]:
from sklearn.preprocessing import OneHotEncoder
encoded = []
for feature in object:
  enc_feat = OneHotEncoder().fit_transform(df[feature].values.reshape(-1,1)).toarray()
  n = df[feature].nunique()
  cols = ['{}_{}'.format(feature, n) for n in range(1, n+1)]
  encoded_df = pd.DataFrame(enc_feat, columns = cols)
  encoded_df.index = df.index
  encoded.append(encoded_df)

In [ ]:
final = pd.concat([df, *encoded], axis = 1)

In [ ]:
final.head()

Class  menopause  node-caps  ...  breast-quad_5  irradiat_1  irradiat_2
0      1          2          0  ...            1.0         1.0         0.0
1      1          2          0  ...            0.0         1.0         0.0
2      1          0          0  ...            0.0         1.0         0.0
3      1          2          0  ...            0.0         1.0         0.0
4      1          0          0  ...            0.0         1.0         0.0

[5 rows x 24 columns]

In [ ]:
final.drop(object, axis = 1, inplace = True)

In [ ]:
final.head()

Class  deg-malig  mean-tumor  ...  breast-quad_5  irradiat_1  irradiat_2
0      1          2        22.0  ...            1.0         1.0         0.0
1      1          2        22.0  ...            0.0         1.0         0.0
2      1          2        17.0  ...            0.0         1.0         0.0
3      1          2         2.0  ...            0.0         1.0         0.0
4      1          2        17.0  ...            0.0         1.0         0.0

[5 rows x 19 columns]

In [ ]:
final.shape

(285, 19)

In [ ]:
x = final.drop('Class', axis = 1).values
y = final['Class'].values

In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xtrain = sc.fit_transform(xtrain)
xtest = sc.transform(xtest)

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(xtrain, ytrain)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
ypred = classifier.predict(xtest)

In [ ]:
cm = confusion_matrix(ytest, ypred)
cm

array([[ 4, 17],
       [ 1, 35]])

In [ ]:
accuracy_score(ytest, ypred)

0.6842105263157895

In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = xtrain, y = ytrain, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 75.02 %
Standard Deviation: 7.31 %


In [ ]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [0.25, 0.5, 0.75, 1], 'kernel': ['linear']},
              {'C': [0.25, 0.5, 0.75, 1], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)

In [ ]:
grid_search.fit(xtrain, ytrain)

GridSearchCV(cv=10, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=0, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=-1,
             param_grid=[{'C': [0.25, 0.5, 0.75, 1], 'kernel': ['linear']},
                         {'C': [0.25, 0.5, 0.75, 1],
                          'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,
                                    0.9],
                          'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

In [ ]:
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Best Accuracy: 75.00 %
Best Parameters: {'C': 0.75, 'gamma': 0.2, 'kernel': 'rbf'}


In [ ]:
from imblearn.over_sampling import RandomOverSampler

In [ ]:
os = RandomOverSampler(0.6)

In [ ]:
xover, yover = os.fit_resample(x,y)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
from collections import Counter

In [ ]:
print('The Number before sampling{}'.format(Counter(y)))
print('The Number After sampling{}'.format(Counter(yover)))

The Number before samplingCounter({1: 200, 0: 85})
The Number After samplingCounter({1: 200, 0: 120})


In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(xover, yover, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xtrain = sc.fit_transform(xtrain)
xtest = sc.transform(xtest)

In [ ]:
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(xtrain, ytrain)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
ypred = classifier.predict(xtest)
cm = confusion_matrix(ytest, ypred)
cm

array([[ 6, 15],
       [ 3, 40]])

In [ ]:
accuracy_score(ytest, ypred)


0.71875

In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = xtrain, y = ytrain, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 66.78 %
Standard Deviation: 8.92 %


In [ ]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [0.25, 0.5, 0.75, 1], 'kernel': ['linear']},
              {'C': [0.25, 0.5, 0.75, 1], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)

In [ ]:
grid_search.fit(xtrain, ytrain)

GridSearchCV(cv=10, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=0, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=-1,
             param_grid=[{'C': [0.25, 0.5, 0.75, 1], 'kernel': ['linear']},
                         {'C': [0.25, 0.5, 0.75, 1],
                          'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,
                                    0.9],
                          'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

In [ ]:
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Best Accuracy: 71.46 %
Best Parameters: {'C': 1, 'gamma': 0.6, 'kernel': 'rbf'}


In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 2)
xtrain = pca.fit_transform(xtrain)
xtest = pca.transform(xtest)

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(xtrain, ytrain)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
ypred = classifier.predict(xtest)
cm = confusion_matrix(ytest, ypred)
cm

array([[ 7, 14],
       [ 1, 42]])

In [ ]:
accuracy_score(ytest, ypred)

0.765625

In [ ]:
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(xtrain, ytrain)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
ypred = classifier.predict(xtest)
cm = confusion_matrix(ytest, ypred)
cm

array([[ 4, 17],
       [ 1, 42]])

In [ ]:
accuracy_score(ytest, ypred)

0.71875

In [ ]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [0.25, 0.5, 0.75, 1], 'kernel': ['linear']},
              {'C': [0.25, 0.5, 0.75, 1], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)

In [ ]:
grid_search.fit(xtrain, ytrain)

GridSearchCV(cv=10, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=0, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=-1,
             param_grid=[{'C': [0.25, 0.5, 0.75, 1], 'kernel': ['linear']},
                         {'C': [0.25, 0.5, 0.75, 1],
                          'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,
                                    0.9],
                          'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

In [ ]:
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Best Accuracy: 68.34 %
Best Parameters: {'C': 0.75, 'gamma': 0.3, 'kernel': 'rbf'}
